export function createPortal(children: any, container: any, ...args: any[]): any;
export function evalInReactContext(injection: any): any;
export function findDOMNode(componentOrElement: any): any;
export function flushSync(fn: any, a: any): any;
export function hotCleanup(): void;
export function hotRenderWithHooks(current: any, render: any): any;
export function hydrate(element: any, container: any, callback: any): any;
export function render(element: any, container: any, callback: any): any;
export function setHotElementComparator(newComparator: any): void;
export function unmountComponentAtNode(container: any): any;
export function unstable_batchedUpdates(fn: any, a: any): any;
export function unstable_createPortal(...args: any[]): any;
export function unstable_createRoot(container: any, options: any): any;
export function unstable_flushControlled(fn: any): void;
export function unstable_interactiveUpdates(fn: any, a: any, b: any): any;
export function unstable_renderSubtreeIntoContainer(parentComponent: any, element: any, containerNode: any, callback: any): any;
